codestates-seb/seb42_main_032

- tikkle-be/build.gradle
- tikkle-be/src/main/java/DabuOps/tikkle/category/entity/Category.java
- tikkle-be/src/main/java/DabuOps/tikkle/category/repogitory/CategoryRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Member.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthAttribute.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthController.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/OAuthUserService.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/SecurityConfiguration.java
- tikkle-be/src/main/resources/templates/index.html
- tikkle-be/src/main/resources/templates/login.html
- tikkle-be/src/test/java/DabuOps/tikkle/TikkleApplicationTests.java
> feat: OAuth2.0 Google Login

- tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
- tikkle-be/src/test/java/DabuOps/tikkle/TikkleApplicationTests.java
- tikkle-be/src/test/java/DabuOps/tikkle/member/controller/MemberControllerTest.java
[fix] MemberControllerTest.java error 해결
> [fix] MemberControllerTest.java error 해결

- tikkle-fe/.pnp.cjs
- tikkle-fe/package.json
- tikkle-fe/src/App.tsx
- tikkle-fe/src/components/layout/Transaction.tsx
- tikkle-fe/yarn.lock
> Feat fe/transaction

- tikkle-be/src/docs/asciidoc/index.adoc
- tikkle-be/src/main/java/DabuOps/tikkle/global/dto/LogInMemberDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/global/exception/ExceptionCode.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/controller/MemberController.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/repository/MemberRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberService.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceStub.java
- tikkle-be/src/test/java/DabuOps/tikkle/TikkleApplicationTests.java
- tikkle-be/src/test/java/DabuOps/tikkle/global/WithMemberDetailsSecurityContextFactory.java
- tikkle-be/src/test/java/DabuOps/tikkle/global/WithMockCustomMember.java
- tikkle-be/src/test/java/DabuOps/tikkle/member/controller/MemberControllerTest.java
Feat be/member memberserivce 구현
> Feat be/member memberserivce 구현

- tikkle-be/src/main/java/DabuOps/tikkle/TikkleApplication.java
- tikkle-be/src/main/java/DabuOps/tikkle/category/repository/categoryRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/repository/MemberRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/member/service/MemberServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/entity/MemberCategory.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceStub.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
- tikkle-be/src/test/java/DabuOps/tikkle/member_category/controller/MemberCategoryControllerTest.java
[fix] entity mapping 연관관계수정 밎 빌드, run 가능하게 수정
> [fix] entity mapping 연관관계수정 밎 빌드, run 가능하게 수정

- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
> [FIX] make it run

- tikkle-fe/src/components/UserInput.tsx
- tikkle-fe/src/components/layout/Header.tsx
- tikkle-fe/src/pages/Home.tsx
- tikkle-fe/src/pages/SignUp.tsx
- tikkle-fe/src/pages/UserSetting.tsx
- 로그인 페이지와 배경 사진 및 투명도 통일
- 로고, 버튼, 문구 사이 간격 조정
> Add page layout

- tikkle-be/src/main/java/DabuOps/tikkle/global/utils/MonthlyTransactionHistoriesDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/controller/MemberCategoryController.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/member_category/service/MemberCategoryServiceStub.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/dto/TransactionHistoryDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/entity/TransactionHistory.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/repository/TransactionHistoryRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryService.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceImpl.java
- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/service/TransactionHistoryServiceStub.java
- tikkle-be/src/main/resources/static/docs/index.html
- tikkle-be/src/test/java/DabuOps/tikkle/member_category/controller/MemberCategoryControllerTest.java
transactionHistory 서비스 로직 구현 완?료
> Feat be/transaction history 

- tikkle-be/src/main/java/DabuOps/tikkle/oauth/controller/OAuthController.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/service/OAuthService.java
[Fix] OAuth Login UserInfo Conntect
> [Fix] OAuth Login UserInfo Conntect

- tikkle-be/src/main/java/DabuOps/tikkle/oauth/controller/OAuthController.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/service/OAuthService.java
[Fix] OAuth Login UserInfo Connect
> [Fix] OAuth Login UserInfo Connect

- tikkle-be/src/main/java/DabuOps/tikkle/oauth/service/OAuthService.java
> [Feat] Google OAuth2.0 Login

- tikkle-be/src/main/java/DabuOps/tikkle/member/entity/Member.java
[make] member initdate have a default
> [make] member initdate have a default

- tikkle-be/src/main/java/DabuOps/tikkle/account/entity/Account.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/config/RestTemplateConfig.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/controller/UserAuthController.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/dto/AccountInfoDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/dto/ResList.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/dto/TokenResponseDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/service/UserAuthService.java
[Feat] Get AccountInfo, AccountNum
> [Feat] Get AccountInfo, AccountNum

- tikkle-be/src/main/java/DabuOps/tikkle/transaction_history/controller/TransactionHistoryController.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/mapper/AccountTransactionMapper.java
- tikkle-be/src/main/java/DabuOps/tikkle/userauth/service/UserAuthService.java
> Feat be/transaction history

- tikkle-be/src/main/java/DabuOps/tikkle/userauth/service/UserAuthService.java
- tikkle-be/src/main/resources/application-prod.yml
- tikkle-be/src/main/resources/application.yml
- tikkle-be/src/main/resources/gradle.yml
> [Fix] Github Secret Value

- tikkle-be/src/main/java/DabuOps/tikkle/oauth/config/SecurityConfiguration.java
[Fix] Security Config FilterChain
> [Fix] Security Config FilterChain

- tikkle-fe/src/pages/Login.tsx
- tikkle-fe/vite.config.ts
> Resolve #154

- tikkle-be/src/main/java/DabuOps/tikkle/account/controller/AccountController.java
- tikkle-be/src/main/java/DabuOps/tikkle/account/entity/Account.java
- tikkle-be/src/main/java/DabuOps/tikkle/account/repository/AccountRepository.java
- tikkle-be/src/main/java/DabuOps/tikkle/account/service/AccountService.java
- tikkle-be/src/main/java/DabuOps/tikkle/account/service/AccountServiceImpl.java
[fix] get mapping for memberId
> [fix] get mapping for memberId

- tikkle-fe/src/components/UserInput.tsx
- tikkle-fe/src/pages/UserSetting.tsx
> Feat fe/usersetting

- tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
[refactoring] memberResponse memberId -> id
> [refactoring] memberResponse memberId -> id

- tikkle-be/src/main/java/DabuOps/tikkle/member/dto/MemberDto.java
[refactoring] memberResponse add picture
> [refactoring] memberResponse add picture

- tikkle-fe/src/components/budget_setting/BudgetDropdown.tsx
> close #252

- tikkle-fe/src/components/curation/Editing.tsx
- tikkle-fe/src/pages/CurationView.tsx
GET 요청 및 CSS 완료
- params 추가한 GET 요청 작동 여부 확인
- 좋아요 클릭 시, PATCH 요청으로 좋아요 개수 ++
> Feat fe/curationview

- tikkle-be/src/main/java/DabuOps/tikkle/curation/dto/CurationDto.java
- tikkle-be/src/main/java/DabuOps/tikkle/curation/mapper/CurationMapper.java
- tikkle-be/src/main/java/DabuOps/tikkle/oauth/config/SecurityConfiguration.java
[refactoring] add memberName to curationResponseDto
> [refactoring] add memberName to curationResponseDto
